let input = document.querySelector(".vJwDU")
let text = document.querySelector(".vJwDU")
let textarea = document.querySelector(".er8xn")
let btn = document.querySelector(".X86VN")
let visible = false
let temp = null

let json_data = {
    "chapter1": {
      "Error messages generated by commands are sent where by default?": "STDERR",
      "2": "number2",
      "3": "number3",
      "4": "number4"
    },
    "chapter2": {
      "1": "number1",
      "2": "number2",
      "3": "number3",
      "4": "number4"
    }

}
let data = JSON.parse(JSON.stringify(json_data))


btn.addEventListener('click', (e) => {
  let output = document.querySelector(".ryNqvb")  

  if (visible == false) {
    if (Object.keys(data["chapter1"]).includes(text.textContent) == true) {
      temp = output.textContent
      output.textContent = data["chapter1"][text.textContent]
      visible = true
    }
  } else {
    output.textContent = temp
    visible = false
  }
});

textarea.addEventListener("input", (e) => {
  let output = document.querySelector(".ryNqvb")  
  temp = output.textContent
  visible = false
})